// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSERIF_12_FONT_ID (85340443)
#define NOTOSERIF_14_FONT_ID (-1367885987)
#define NOTOSERIF_16_FONT_ID (1428909134)
#define NOTOSERIF_18_FONT_ID (-501438527)
#define NOTOSANS_12_FONT_ID (2057568286)
#define NOTOSANS_14_FONT_ID (-1589315735)
#define NOTOSANS_16_FONT_ID (1669013660)
#define NOTOSANS_18_FONT_ID (37077304)
#define UI_10_FONT_ID (982653217)
#define UI_12_FONT_ID (-22104740)
#define SMALL_FONT_ID (674098198)
#define TERMINAL_MONO_8_FONT_ID (1159244878)
#define TERMINAL_MONO_10_FONT_ID (-678460070)
#define TERMINAL_MONO_12_FONT_ID (-365074266)
#define TERMINAL_MONO_14_FONT_ID (-795326088)
#define TERMINAL_MONO_16_FONT_ID (2014276361)
#define TERMINAL_MONO_18_FONT_ID (-1917429270)
#define TERMINAL_MONO_20_FONT_ID (-1095500891)
#define TERMINAL_MONO_22_FONT_ID (-1883589883)
#define TERMINAL_MONO_24_FONT_ID (-81583622)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TERMINAL_MONO_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TERMINAL_MONO_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TERMINAL_MONO_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TERMINAL_MONO_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TERMINAL_MONO_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TERMINAL_MONO_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TERMINAL_MONO_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TERMINAL_MONO_22_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TERMINAL_MONO_24_FONT_ID != 0, "Font ID collision with sentinel");
